# Generated by Django 5.2.6 on 2025-10-01 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0004_remove_wallet_onchain_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.TextField(unique=True)),
                ('amount_sats', models.BigIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='wallets.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='LightningPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sats', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('confirmed', 'Confirmed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightning.lightninginvoice')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallets.wallet')),
            ],
        ),
    ]
