# Generated by Django 5.2.6 on 2025-09-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_address', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('fee', models.PositiveIntegerField(default=0)),
                ('txid', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('spent', models.BooleanField(default=False)),
            ],
        ),
    ]
