# Generated by Django 5.2.6 on 2025-09-30 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sender_utxo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_tx', to='wallets.utxo'),
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='transactioninput',
            name='utxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallets.utxo'),
        ),
        migrations.AddField(
            model_name='transactionoutput',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='transactions.transaction'),
        ),
    ]
