# Generated by Django 5.2.6 on 2025-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='customeruser',
            old_name='crypto_address',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
