# Generated by Django 5.2.6 on 2025-09-30 08:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('onchain_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('lightning_balance', models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UTXO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255)),
                ('vout', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('confirmations', models.IntegerField(default=0)),
                ('script_pub_key', models.CharField(blank=True, max_length=255, null=True)),
                ('spent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utxos', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('txid', 'vout')},
            },
        ),
    ]
