# Generated by Django 5.2.6 on 2025-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
