# Generated by Django 5.2.6 on 2025-10-01 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_wallet_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='onchain_balance',
        ),
    ]
