# Generated by Django 5.2.4 on 2025-09-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactionoutput',
            name='spent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender_utxo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='used_in_tx', to='wallets.utxo'),
        ),
    ]
